### ISSUE TITLE
GPU RAM exhaustion!!

### ISSUE THREAD

**Issue by vaibhawkhemka** [DarlingHang/st-nerf#3]
@DarlingHang 
what is minimum RAM of GPU required for the project as the process is being killed in my system due to RAM exhaustion.??
Please Guide me..

**Comment by DarlingHang** [comment]
Hi! We have tested our codes on one NVIDIA GeForce RTX 3090, which has ~24G memory. If you ran into RAM exhaustion, I suggest you try reduce sampling number in the config file (COARSE_RAY_SAMPLING and FINE_RAY_SAMPLING). This is may sacrifice the quality of the result.

**Comment by vaibhawkhemka** [comment]
@DarlingHang I tried reducing coarse ray sampling and fine ray sampling. But getting the error below and process is being killed automatically:
![st_nerf](https://user-images.githubusercontent.com/46538042/132624167-aeffa370-a3db-4d62-9bec-0c400edfe6e5.png)

**Comment by Jiakai-Zhang** [comment]
> @DarlingHang I tried reducing coarse ray sampling and fine ray sampling. But getting the error below and process is being killed automatically:
> ![st_nerf](https://user-images.githubusercontent.com/46538042/132624167-aeffa370-a3db-4d62-9bec-0c400edfe6e5.png)

Hi, I guess it is a memory out error, we have to generate all of the rays and load them into memory, we didn't optimize this part because we are training on a server with 300g memory...It would be not so hard to optimize if we simply add a mode to training our network per image, it may give a little performance difference but I guess it will be fine, I will try to optimize it when I have time.

Some naive solutions:
1. I guess you want to train our network: you can modify the training resolution on config file, you can change (1920,1080) to (480, 270).
2. Decrease the frame number: it is on config file-- DATASETS.FRAME_NUM.

These solutions may give a low-resolution and incomplete reproducing of our trained model, please feel free to use our pre-trained model to reproduce our results.

**Comment by semchan** [comment]
I guess it is running here"                pts = torch.matmul(inv_Ts,vs) #(M,N,4,1)

                pts_max = torch.max(pts, dim=1)[0].squeeze() #(M,4)
                pts_min = torch.min(pts, dim=1)[0].squeeze() #(M,4)", it pop out of memory, not for training. May I know have you someone fixed it?thanks a lot.

**Comment by Jiakai-Zhang** [comment]
> 

We are trying to calculate near_far for each camera here, there indeed will be a large memory cost, if you meet a memory out error here, you can try to downsample your pointcloud or manually provide a bounding box points here.

I hope it will be helpful for you.

Cheers,

**Comment by semchan** [comment]
> > 
> 
> We are trying to calculate near_far for each camera here, there indeed will be a large memory cost, if you meet a memory out error here, you can try to downsample your pointcloud or manually provide a bounding box points here.
> 
> I hope it will be helpful for you.
> 
> Cheers,

Thanks. I have already fixed it by modifying: `pts = torch.matmul(inv_Ts,vs) #(M,N,4,1)` to `                M,_,_,_ = inv_Ts.size()
                N,_,_ = vs.size()
                inv_Ts = inv_Ts.expand(M,N,4, 4)
                pts = torch.Tensor(M,N,4,1)
                for i in range(M):
                    inv_Ts_temp = inv_Ts[i]
                    pts_temp = torch.bmm(inv_Ts_temp,vs)
                    pts[i] = pts_temp,` and it greatly reduce the GPU memory. thanks.
